name: C/C++ code linter (clang-tidy and clang-format)
description: Automatically checks pull requests changes with clang-tidy, clang-format and posts the comment with result.
author: shenxianpeng
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  style: # the specific style rules
    description: "The style rules to use (defaults to 'llvm'). Set this to file to make 'file' to have clang-format use the closest relative .clang-format file."
    required: false
    default: 'llvm'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.style }}
