name: C/C++ code linter (clang-tidy and clang-format)
description: Automatically checks pull requests changes with clang-tidy, clang-format and posts the comment with result.
author: shenxianpeng
branding:
  icon: 'check-circle'
  color: 'green'
runs:
  using: 'docker'
  image: 'Dockerfile'
