name: cpp-linter-action
description: Automatically checks pull requests changes with clang-tidy, clang-format, and cppcheck and posts the comment with result.
author: shenxianpeng
branding:
  icon: alert-circle
  color: green
runs:
  using: 'docker'
  image: 'Dockerfile'
