name: build-dev-docs

on:
  push:
  pull_request:
    types: [opened]

jobs:
  build-mkdocs-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install doc's deps
        run: |
          python3 -m pip install -r docs/requirements.txt
          python3 -m pip install .
      - name: Build docs
        run: mkdocs build
      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: "cpp linter action dev docs"
          path: |
            site/**
      - name: push to gh-pages
        run: mkdocs gh-deploy
