name: cpp-linter

on:
  push:
  pull_request:
    types: [opened]

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
<<<<<<< HEAD:.github/workflows/test.yml
      # - uses: shenxianpeng/cpp-linter-action@master
      - uses: 2bndy5/cpp-linter-action@parse-better
=======
      - name: C/C++ Lint Action
        uses: shenxianpeng/cpp-linter-action@master
>>>>>>> main:.github/workflows/cpp-linter.yml
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: |
          echo "Some files failed the linting checks!"
        # for actual deployment
        # run: exit 1
