name: Test action

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      # - uses: shenxianpeng/cpp-linter-action@master
      - uses: 2bndy5/cpp-linter-action@output-exit-code
        id: linter
        with:
          style: file
          extensions: 'cpp'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Fail fast?!
        if: steps.linter.checks-failed > 0
        run: |
          echo "Some files failed the linging checks!"
        # for actual deployment
        # run: exit 1
