name: Test action

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 2bndy5/cpp-linter-action@add-input
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
